server:
  port: 8101
  servlet:
    context-path: /
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
